version: "3.9"
name: deboinvest
services:
  db-postgres-11:
    image: postgres:11.7-alpine
    container_name: "deboinvest-db"
    ports:
      - "4600:5432"
    environment:
      - POSTGRES_DB=deboinvest
      - POSTGRES_SCHEMA=deboinvest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init_config_database.sh:/docker-entrypoint-initdb.d/init_config_database.sh
      - deboinvestPgVolume:/var/lib/postgresql/data
  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: "deboinvest-mailhog"
    restart: "always"
    ports:
      - "127.0.0.1:5205:1025"
      - "127.0.0.1:5206:8025"
volumes:
  deboinvestPgVolume: { }
    # external: true
    # name: parcPgVolume